### ISSUE TITLE
Support .cjs extension for configuration file

### ISSUE THREAD

**Issue by taraldr** [raineorshine/npm-check-updates#1051]
- [✓ ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [✓ ] I am using the latest version of `npm-check-updates`
- [✓ ] I am using `node >= 12`

---------------------------

## Steps to Reproduce
Create config file with `.cjs` file extension.

## Current Behavior
ncu does not find the config file.

## ~~Expected~~ Desired Behavior
ncu finds and uses the config file.

**Comment by raineorshine** [comment]
Thanks for the suggestion! Could you provide some more background? What is a cjs file? Is it the same format as an rc file?

As this is not a commonly requested feature, a PR would be the best strategy to get it added.

**Comment by GeoffreyBooth** [comment]
A `.cjs` file is a CommonJS JavaScript file: https://nodejs.org/api/packages.html#:~:text=Files%20ending%20with%20.cjs, https://babeljs.io/docs/en/config-files#:~:text=babel.config.cjs%20and%20.babelrc.cjs.

It’s common for CommonJS CLI tools to accept `.cjs` files as config files, so that projects with `"type": "module"` in their `package.json` have a way to specify the configuration for the CommonJS tool.

**Comment by raineorshine** [comment]
Ah, of course. Thanks for the explanation.

npm-check-updates uses `rc-config-loader`, which does not support .cjs by default. I have opened a PR there: https://github.com/azu/rc-config-loader/pull/16

Once it gets merged, I'll bump the dependency and publish a new release.

**Comment by raineorshine** [comment]
@azu is very fast! 

Published in `v12.5.6`
