### ISSUE TITLE
TypeError: ncu is not a function

### ISSUE THREAD

**Issue by atomicrobokid** [raineorshine/npm-check-updates#1199]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x ] I am using the latest version of `npm-check-updates`
- [x ] I am using `node >= 14`

---

## Steps to Reproduce

```js
import ncu from 'npm-check-updates'

export const upgrades = await ncu({
    // Pass any cli option
    packageFile: './package.json',
    upgrade: false,
    interactive: false,
    filter: 'npm-check-updates'
})

console.log(upgrades)

```

Steps:

New project using `"npm-check-updates": "16.3.0",`

Use recommended config, run `node foo.js`

## Current Behavior

Following the README, I have set up a basic js file with the config above. When i run that I get 
```
export const upgrades = await ncu({
                              ^

TypeError: ncu is not a function
```

I am used Node `v16.17.0` and npm `8.15.0`. Tried adding and removing `"type": "module"` from my package.json. Tried in both vanilla js and compiling with tsc.

## Expected Behavior

Expected to successfully log

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

I'm not quite sure what the issue is, as `npm-check-updates` exports a function `run` as the default export:

https://github.com/raineorshine/npm-check-updates/blob/373441ede5e6d252b7a82f9f0751df9a0c85cb93/src/index.ts#L349

However, it is also exported as a named function, so you can try `ncu.run` or `import { run } from 'npm-check-updates'. If that doesn't work , try `import * as ncu from 'npm-check-updates'`.

https://github.com/raineorshine/npm-check-updates/blob/373441ede5e6d252b7a82f9f0751df9a0c85cb93/src/index.ts#L161-L164

Here is a sample Typescript repo that compiles correctly with the documented usage:

https://github.com/raineorshine/ncu-test-import-as-module/blob/main/src/index.ts

It basically just consists of:

```ts
import ncu from 'npm-check-updates'

const upgrades = await ncu()
console.log(upgrades)
```

However, maybe the method of importing is different if using node `v16` without Typescript.

**Comment by atomicrobokid** [comment]
@raineorshine 

Ahh that was the trick, thanks! tThis is what I needed in the end:
```js
import * as ncu from 'npm-check-updates'

async function logResult() {
  return await ncu.run({
    packageFile: './package.json',
    registry: 'myinternalregistry.com/abcd',
  })
}
console.log(await logResult());
```

My final stumbling block is I my packages live in an internal company npm registry that uses Artifactory. For the usual `npm i` this uses the config set in the `.npmrc` file as specified by the npm docs. However it seems `ncu` does not respect the `.npmrc` file. Specifying the registry url, I cannot for the life of me figure out how I pass login details via that method (hence the `.npmrc` file) - Is there any way to get `ncu` to load/read from `.npmrc`??

Thanks!
