### ISSUE TITLE
storybook library version down from beta to alpha

### ISSUE THREAD

**Issue by yogarasu** [raineorshine/npm-check-updates#1253]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Use this repository
https://github.com/revoltage-inc/tmp-nextjs

Run ncu command shortcut script

```zsh
npm run update
```

## Current Behavior

Downgraded from beta to alpha.

<img width="441" alt="スクリーンショット 2022-12-21 2 56 57" src="https://user-images.githubusercontent.com/68766032/208734218-cc8626a5-78d5-46c7-8927-056a7133eeaa.png">

## Expected Behavior

Not be version down.

**Comment by raineorshine** [comment]
Unfortunately the owner of `@storybook/react-vite` is publishing prerelease versions (*-alpha.*) to the `latest` tag which is not conventional nor recommended:

```js
{
  future: '7.0.0-alpha.34',
  latest: '7.0.0-alpha.25',
  next: '7.0.0-beta.13'
}
```

`npm-check-updates` upgrades to the `latest` tag by default, so that's why you are getting `7.0.0-alpha.25`. I recommend opening an issue in the appropriate @storybook repos to discourage this publishing behavior. In the mean time, you can use `npm-check-updates --target @next` to upgrade to the `next` tag (or add a custom `target` function in your ncurc with `name.startsWith('@storybook') ? '@next' : '@latest'`).

`npm-check-updates` will not downgrade *within* a tag, but if you switch tags it will do as told and upgrade to the requested tag (`latest` being the default). If we made `beta` → `alpha` a special case and prevented downgrading, it would potentially break workflows that depend on switching between different tags. This was a major goal in #1134.

All that to say, you're not wrong, but the current behavior will likely be preserved because 1) the root cause is a package owner breaking publishing conventions, 2) changing npm-check-updates behavior would cause regressions, 3) there is an easy workaround of specifying `--target next`.

**Comment by yogarasu** [comment]
@raineorshine 
Thank you for your polite answer, I learned a lot.
