### ISSUE TITLE
Latest release on github is 16.4.0, tags and ncu itself say latest version is 16.6.0

### ISSUE THREAD

**Issue by gabriellend** [raineorshine/npm-check-updates#1254]
Just wondering if I should upgrade or not and why the tags don't match the releases? Thank you!

**Comment by raineorshine** [comment]
I don't always draft a Github release to match each minor release, because I don't want to bombard subscribers with notifications :). However, it is unfortunate that Github marks the last release as `latest` even when it doesn't match the `latest` tag on the npm registry.

- `16.4.0` added the rarely used `packageManager` value to the list of valid `--dep` options
- `16.5.0` added `--format time` to show the publish time of each suggested upgrade

**Comment by gabriellend** [comment]
@raineorshine Thank you for clearing that up!

**Comment by raineorshine** [comment]
Oops, I meant `16.5.0` and `16.6.0`. Edited :).
