### ISSUE TITLE
No support for PNPM globals

### ISSUE THREAD

**Issue by ekwoka** [raineorshine/npm-check-updates#1265]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`
---

## Steps to Reproduce

Install package globally with pnpm

`ncu -g -p pnpm`

Only checks npm

## Expected
have some flag to also check global pnpm

Seems here: https://github.com/raineorshine/npm-check-updates/blob/main/src/lib/getPackageManager.ts#LL23C24-L23C24 that pnpm is just defaulted to npm regardless.

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

Since pnpm is a drop-in replacement for npm, npm-check-updates just uses npm to check versions from the npm registry. However, this clearly does not work for global packages.

I added an initial implementation that uses `pnpm -g --json ls` to get pnpm global packages. There are probably some options that do not get propagated correctly, but it covers the base case when tested on my machine. 

Published to `v16.6.5`. Please give try it out at your convenience and we an iterate on it if we need to add support for other options.

**Comment by ekwoka** [comment]
Wow, very fast! I was thinking maybe I'd get to diving in and seeing what I can find this weekend.
