### ISSUE TITLE
Downgrade to previous version

### ISSUE THREAD

**Issue by Dennis-Do** [raineorshine/npm-check-updates#1266]
How to downgrade to a version smaller than X using the filter to select packages start with "any-string" ?

**Comment by raineorshine** [comment]
npm-check-updates does not support downgrading unless switching tags. This is by design to provide stronger guarantees around preserving version numbers and more flexibility around using betas and prerelease versions.

The closest thing we have is `--target minor` and `--target patch` for limiting upgrades: https://github.com/raineorshine/npm-check-updates#target

e.g. `ncu --target minor any-string*

**Comment by Dennis-Do** [comment]
Unfortunately nowadays it is sometimes the case that greatest and latest are like beta or pre-release. It would therefore be useful to be able to switch back to the last major release before Greatest.

Alternativly skip major releases that are younger than 2 days for example. Is it possible to filter by release date?

**Comment by raineorshine** [comment]
> Alternativly skip major releases that are younger than 2 days for example. Is it possible to filter by release date?

We have an open ticket #833, but nobody is working on it currently. Would be a great feature.
