### ISSUE TITLE
exclude peer checking doesn't work

### ISSUE THREAD

**Issue by its-dibo** [raineorshine/npm-check-updates#1288]
- [x ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ x] I am using the latest version of `npm-check-updates`
- [ x] I am using `node >= 14.14`

---
I need to override the value `peer: true` specified in the .ncurc.js file through the cli.
it seems that only `--peer` works, but the following don't work `--peer=false`, `--peer false`, `--no-peer`

it seems that the CLI options don't override the config file.
by experimenting, this happens when setting `deep` to true

**Comment by raineorshine** [comment]
Yes, curious omission.

I have added support for `--peer false` (likewise for all boolean arguments) and published to `v16.9.0`.

**Comment by raineorshine** [comment]
Unfortunately this had to be reverted as it caused a regression (#1292).

I implemented the `--peer false` functionality by adding an optional variable to the commander option for each boolean option. This broke two uses that were not covered by the tests:

- combining boolean and non-boolean short flags (e.g. `ncu -gp pnpm`)
- specifying rest arguments after a unary boolean flag (e.g. `ncu --verbose [NAME]`)

We will need to think of a different approach to override boolean config values in the cli. Technically, `ncu -gp pnpm` is not ambiguous since pnpm is not a valid boolean value, and `--peer false` is only ambiguous if the [false](https://www.npmjs.com/package/false) npm package is used, which is probably rather few. Nevertheless, it does seem to interfere with cli parsing, so a different approach is preferred.

`--no-peer` would be clear and not cause any conflicts. I just need to add it discretely so we don't get "duplicate" entries for every boolean option in the help system.

**Comment by raineorshine** [comment]
Okay, I added a `--no-peer` implementation. Published in `v16.10.5`.
