### ISSUE TITLE
[Feature Request] Add JSON Schema for config file

### ISSUE THREAD

**Issue by josh-hemphill** [raineorshine/npm-check-updates#1289]
I planned on making a PR, but I tried using both the major `TS -> JSON Schema` libraries to add it, and both of them failed in weird ways.
So maybe just creating a manual one would be better for now.
Figured I'd at least open this issue to track this though.

When you start writing a lot of `.ncurc` files, having completions for them becomes very appealing.

**Comment by raineorshine** [comment]
Hi! Thanks for the suggestion.

This worked for me:

```
npx typescript-json-schema tsconfig.json RunOptions
```

Adding defaults just requires a small tweak to the build-options script:

```diff
diff --git a/src/scripts/build-options.ts b/src/scripts/build-options.ts
index 3b39761..5aeb75b 100644
--- a/src/scripts/build-options.ts
+++ b/src/scripts/build-options.ts
@@ -73,7 +73,7 @@ const renderOption = (option: CLIOption<unknown>) => {
   const defaults =
     // do not render default empty arrays
     option.default && (!Array.isArray(option.default) || option.default.length > 0)
-      ? ` (default: ${JSON.stringify(option.default)})`
+      ? `\n   * @default ${JSON.stringify(option.default)}\n  `
       : ''
```

Now, where does this json schema go so that it's useful to people?

**Comment by josh-hemphill** [comment]
Hmm. I guess trying to use them programmatically was a bad idea. 😆
I don't know of anything that automatically looks for the schemas in any particular place. I'd assume just anywhere obvious under version control.
I had planned on putting the URL to it into my VSCode settings list of schemas.
If there's enough demand/interest for there to be a VS Code extension at some point, it could automatically register it.

**Comment by raineorshine** [comment]
Yeah, when I tried to add programmatic usage to the build process it didn't work for me either, at least not straightforwardly. I'm just spawning it in a child process at this point. The repo looks a bit undermaintained given all the unanswered issues, so I'm not going to the trouble of a bug report.

Let me know if you have any feedback! It has some defaults that it picks up from the jsdocs, but otherwise it is just a basic output. I'm sure we can refine it for better usability.

Source: https://github.com/raineorshine/npm-check-updates/blob/main/src/types/RunOptions.json
Raw: https://raw.githubusercontent.com/raineorshine/npm-check-updates/main/src/types/RunOptions.json

**Comment by josh-hemphill** [comment]
Thank you for figuring that out. It works great. Created a PR to mention it in the README if you want.
