### ISSUE TITLE
Add option to output changelog

### ISSUE THREAD

**Issue by ElPrudi** [raineorshine/npm-check-updates#1294]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

Just found about this package and already love how fast it is. My question is, would it be possible to add an option to output the changelog link for each package? That would make it much easier/faster to update to newer major versions and much more convenient to update in general.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion. This has been proposed and discussed in #570. You may not have found it because it was closed. I reopened it for anyone who would like to attempt the feature. 

It looks like it got stuck on the fact that there is no standard changelog location, and guessing it takes a lot of HTTP requests. It can be done though. 

The closest feature that exists now is [`--format repo`](https://github.com/raineorshine/npm-check-updates#format) which displays the url to the repo next to each upgrade. From there you can click on the changelog or releases if the project has them. 

I will close this issue as a duplicate, but feel free to continue the discussion in #570.
