### ISSUE TITLE
bug: interactive mode should not preselect any versions

### ISSUE THREAD

**Issue by EinfachHans** [raineorshine/npm-check-updates#1317]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14.14`

---

## Current Behavior

In the interactive mode some packages are preselected. If i see correctly all patch and minor updates are preselected? Is this really indeed?

## Expected Behavior

Imo no package should be preselected in interactive mode

**Comment by raineorshine** [comment]
This behavior is intentional. Non-breaking upgrades are selected by default, and breaking upgrades are opt-in.

To deselect all upgrades, press `a`. There is no equivalent to select only non-breaking upgrades with one key press, so we default to this safe upgrade suggestion knowing that it is easy for users to add or reset their selections from there.

**Comment by EinfachHans** [comment]
Mhh maybe not perfect for me then, but deselecting all with "a" works for me, thanks for clarification 👍🏼

**Comment by raineorshine** [comment]
More people requested this feature, so I changed my mind. Added in `v23.1.0`.

```
ncu -i --interactiveSelect none
```

Or in your [ncurc config](https://github.com/raineorshine/npm-check-updates#config-file):

```
{
  "interactiveSelect": "none"
}
```
