### ISSUE TITLE
[FR] ncu -u -E/--save-exact

### ISSUE THREAD

**Issue by wenfangdu** [raineorshine/npm-check-updates#1366]
When running `ncu -u`, how to save the deps as the exact versions? i.e. no version prefix like `^` `~` etc.
![image](https://github.com/raineorshine/npm-check-updates/assets/28700378/efb15eb0-c7b8-427b-8e7b-41b75a5c14d9)
If there's no such way, please consider adding an option like `-E`/`--save-exact` just like `npm install` has this option.

**Comment by raineorshine** [comment]
Hi, thanks for your suggestion.

npm-check-updates preserves your existing version policies, so to save exact versions you would should remove `^` from your package.json.

Adding a separate option `--save-exact` is outside the intended scope of this package.

**Comment by iloveitaly** [comment]
@wenfangdu did you find a solution here?

In my `.npmrc` i have:

```
engine-strict=true
save-exact=true
```

But I'm still getting exact versions being ignored when running:

```
pnpm dlx npm-check-updates --interactive
```

<img width="547" alt="Image" src="https://github.com/user-attachments/assets/f670aa0a-203b-4bc9-91c6-e339633df2d0" />

Here's my day picker version:

```
    "react-day-picker": "8.10.1",
```

**Comment by raineorshine** [comment]
It is the intended behavior for npm-check-updates to upgrade all versions, regardless of how they are specified in your package.json. In fact it is the main purpose of npm-check-updates. 

From the README:

> npm-check-updates upgrades your package.json dependencies to the latest versions, ignoring specified versions.

`npm update` will upgrade your version ranges according to semver and ignore exact versions, so you generally only need `npm-check-updates` in order to *break* your specified versions/version ranges.

You could craft a [filterVersion](https://github.com/raineorshine/npm-check-updates#filterversion) option to only upgrade version ranges:

```sh
ncu --filterVersion "/^[^~]\d/"
```
