### ISSUE TITLE
False positive on @tailwindcss/postcss

### ISSUE THREAD

**Issue by jpike88** [raineorshine/npm-check-updates#1479]
```@tailwindcss/postcss           ^4.0.0-beta.4  →  ^0.0.0-development.1```

This above suggestion is wrong

**Comment by jpike88** [comment]
Also, it's not picking `tailwindcss@4.0.0-beta.6` which I'm still on `tailwindcss@4.0.0-beta.4`

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

The default behavior for npm-check-updates is to upgrade your package.json dependencies to the *latest* versions, ignoring specified versions.

Given the versions that are published on `latest` for these packages, what you are seeing is the expected behavior. 

In the case of `tailwindcss`, npm-check-updates finds that the `latest` version is `3.4.16` and it does not suggest a change, as that would be a downgrade from your specified version of `4.0.0-beta.4`.

```js
$ npm view tailwindcss dist-tags
{
  insiders: '0.0.0-insiders.f875ab9',
  latest: '3.4.16',
  next: '4.0.0-beta.6'
}
```

In the case of `@tailwindcss/postcss`, npm-check-updates finds that the latest version is the prelease version `0.0.0-development.1`. Since version numbers on different prerelease channels cannot be compared (`development` vs `beta`), then npm-check-updates assumes you are switching channels and recommends upgrading to the latest version of `0.0.0-development.1`.

```
$ npm view @tailwindcss/postcss dist-tags
{
  latest: '0.0.0-development.1',
  internal: '0.0.0-internal.b2586d4e',
  next: '4.0.0-beta.6'
}
```

If you would like to upgrade to the `next` tag instead of `latest`, you can do:

```
$ ncu -t @next                                                                                              
Checking /Users/raine/projects/ncu-issues/1479/package.json
[====================] 2/2 100%

 @tailwindcss/postcss  ^4.0.0-beta.4  →  ^4.0.0-beta.6
 tailwindcss            4.0.0-beta.4  →   4.0.0-beta.6
```

If you would like to only upgrade to the `next` tag for tailwind dependencies, you can define a custom [target function](https://github.com/raineorshine/npm-check-updates#target) in your ncurc.js config.
