### ISSUE TITLE
ncu ignores = on versions

### ISSUE THREAD

**Issue by hawkeye64** [raineorshine/npm-check-updates#520]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.12
* npm version: 6.9.0
* npm-check-updates version: 3.1.0

---------------------------

I have in my package.json this: `"strip-ansi": "=3.0.1",`
but ncu will updated it on `ncu -u`

While the = is implied, as opposed to not there at all, I don't think ncu should update. If this package updates to 5.0.1 then it breaks webpack.

**Comment by raineorshine** [comment]
> A leading "=" or "v" character is stripped off and ignored.
https://docs.npmjs.com/misc/semver#versions

ncu exactly matches npm's semantics in order to avoid any confusion. The basic purpose of ncu is to *break* your version ranges. Detecting, managing, and ameliorating breaking changes is your responsibility.

I would recommend running `ncu -x strip-ansi` to exclude the `strip-ansi` module until the compatibility with webpack is fixed.

**Comment by hawkeye64** [comment]
Thanks for the tip!
