### ISSUE TITLE
How to only update all to latest minor version?

### ISSUE THREAD

**Issue by mesqueeb** [raineorshine/npm-check-updates#652]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.
---------------------------

I can't seem to find this anywhere in the readme or the issues.
I want to update all packages to latest minor version, skip all major version bumps.

I tried 
- `ncu -u -m` which only upgraded packages to major bumps
- `ncu -u --semverLevel minor` which says:
> All dependencies match the minor package versions :)

which is not true if I double check by running `yarn outdated`.

Any advice much appreciated!

**Comment by raineorshine** [comment]
To clarify, this means you want, for example:

```
dexie       ^1.0.3  →    ^1.5.0
```

Instead of:

```
dexie       ^1.0.3  →    ^3.0.1
```

Also, are you using exact version numbers or version ranges?

**Comment by mesqueeb** [comment]
Hey @raineorshine 
thanks for your follow-up question!!

Yes, I only use ranges, all with `^`, that's also the default when doing `npm i something`

Now when doing `npm update` it will update all packages to latest minor version, eg. `1.0.0` to `1.5.0` and update the package.json.

There's one project we don't use npm or yarn, but lerna. And it's quite complicated to update packages, so I needed a tool that only modifies the `package.json` file.

THIS IS JUST WHAT I WAS LOOKING FOR! 😄 

So I'd like to do something equivalent to `npm update` that updates all packages from eg. `^1.0.0` to `^1.5.0` just inside the package.json!

Let me know if this is possible. 😉

**Comment by raineorshine** [comment]
Great, that makes perfect sense. Thanks for explaining.

You won't get semver update from `ncu`, although I don't think it would be too hard to add that functionality if you are motivated. You would just need to add a new interface `semver` to the [package manager API](https://github.com/raineorshine/npm-check-updates/tree/master/lib/package-managers) next to `latest`, `greatest`, `newest`, etc.

In the mean time, `--semverLevel major` might suffice if all you're looking for is a non-breaking update, but it doesn't seem to be working when I try it out. Which is strangle because the unit tests are all passing. I think we may need to file a separate bug!

**Comment by raineorshine** [comment]
Added more tests and fixed up a couple edge cases for `--semverLevel`. Published in `v6.0.0`.

**Comment by raineorshine** [comment]
Try `ncu --semverLevel major` and let me know if it works for your use case.

**Comment by mesqueeb** [comment]
@raineorshine Like a charm! This was just what I was looking for! `ncu --semverLevel major` is a life saver!!!!


BTW, I wanna say great job on em the app. It reminded me a lot about `checkvist` which also allows for unlimited nesting and works great with the keyboard. The problems with checkvist are though that it looks really bad, and there's no good mobile version.

I was actually working on a project myself similar to checkvist, to make lists with unlimited indentation and have it usable as either to-do list OR just for taking notes / brain storming.

I have an alpha version, and am now working on a proper design. I'd love your input sometime ;)

keep up the good work!!

**Comment by raineorshine** [comment]
> @raineorshine Like a charm! This was just what I was looking for! `ncu --semverLevel major` is a life saver!!!!

Excellent

> BTW, I wanna say great job on em the app. 

Thanks!

> It reminded me a lot about `checkvist` which also allows for unlimited nesting and works great with the keyboard. The problems with checkvist are though that it looks really bad, and there's no good mobile version.

Yes, I've gotten good feedback on the minimal style of **em** so far. And it's been mobile first since the beginning as it is envisioned to be a "sensemaking companion" on hand at all times.

> I was actually working on a personal side-project myself similar to checkvist, to make lists with unlimited indentation and have it usable as either to-do list OR just for taking notes / brain storming.
> 
> I have an alpha version, and am now working on a proper design. I'd love your input sometime ;)

Sure, happy to chat! Email me or message me on [gitter](https://gitter.im/cybersemics/em).

**Comment by raineorshine** [comment]
FYI `--semverLevel major` was changed to `--target minor` in v8 to better match user expectations:

See: https://github.com/raineorshine/npm-check-updates/blob/master/CHANGELOG.md#800---2020-08-29
