### ISSUE TITLE
lock version of a package

### ISSUE THREAD

**Issue by voxspox** [raineorshine/npm-check-updates#680]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

run `ncu`

## Current Behavior

output for **react** is:

    ...
    react                                            <16.12  →    ^16.13 (red) 
    ...

output for **eslint** is:

    ...
    eslint                                            ^6.8.0  →    ^7.1.0 
    ...

but no output if I put "eslint: <7" into package.json (as expected)

## Expected Behavior

I want to lock the version of a certain package (here react) and expect that it is not displayed by `ncu` and especially not considered by `ncu -i`

**Comment by raineorshine** [comment]
The best way to do this is to add an `.ncurc` file to your project root and exclude `react`:

```js
{
  "reject": [
    "react"
  ]
}
```

Aside from excluding packages, `ncu` will always upgrade past the upper bound of the specified version range. This is by design. In the past, mixed behavior was confusing for many users. Breaking the upper bound is `ncu`'s *raison d'etre*, so it made since to make that an invariant.

`semverLevel` is an exception, but it is not relevant in your case since it applies to all dependencies.

**Comment by voxspox** [comment]
I don't want to complete exclude `react` from updates. I just want to have more control. Thanks for pointing out the `.ncurc` options.

What I still don't understand is that for `react: <16.12` a higher version is proposed and for `eslint: <7` not. It seems that for eslint the rule `< ...` is respected and for react not.

**Comment by raineorshine** [comment]
Aha! You found a bug! "<" should be replaced by a wildcard, as specified in [How dependency updates are determined](https://github.com/raineorshine/npm-check-updates#how-dependency-updates-are-determined). There was a bug that skipped the dependency when "<" was used with a single digit version number. Fixed in f04d00e550ce606893bee77b78ef2a0b2a50246a.

Granular control over upper bounds would be a feature worth considering. At the moment, you can only control the policy for all versions (`--semverLevel`) or granularly exclude dependencies. As a temporary solution, you could use the admittedly ungraceful: `ncu --reject react && ncu --semverLevel major react`.

**Comment by voxspox** [comment]
ok :)
