### ISSUE TITLE
--filter not working properly with packages containing hyphens

### ISSUE THREAD

**Issue by obihill** [raineorshine/npm-check-updates#759]
I'm using `node@10.13.0` and `npm-check-updates@9.2.4`.

The `--filter` flag appears to have an issue when using it with hyphenated package names.

I was trying to use this on `chrome-launcher` and `puppeteer` using the following command:

```
ncu -f chrome-launcher puppeteer
```

Only 1 package shows up i.e. puppeteer. However, when I use commas to delimit like this:

```
ncu -f chrome-launcher,puppeteer
```

Both packages show up. 'Switching to commas for now, but wanted to bring this to your attention for a fix.

**Comment by raineorshine** [comment]
> I was trying to use this on `chrome-launcher` and `puppeteer` using the following command:
> 
> ```
> ncu -f chrome-launcher puppeteer
> ```

Options are space-delimited, so what's happening here is that you are specifying a `--filter` option of `chrome-launcher` and a regular argument of `puppeteer`. Since regular arguments are used to specify a filter also, it is overriding your `-f` option. If you reverse the order you will see that `chrome-launcher` overrides `puppeteer`. You can use either of the following to achieve your aim:

- `ncu chrome-launcher puppeteer`
- `ncu -f "chrome-launcher puppeteer"`

It's an easy mistake to make though, so I should probably require `--filter` OR args but not both.
