### ISSUE TITLE
Add a homebrew formula

### ISSUE THREAD

**Issue by domoritz** [raineorshine/npm-check-updates#846]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

I would like to propose a new feature. It would be great if you could provide a homebrew formula for npm-check-updates so that people can install `brew install npm-check-updates`.

**Comment by raineorshine** [comment]
Thanks for the suggestion. Since they already have npm, what's the advantage of  putting it on homebrew?

**Comment by domoritz** [comment]
I would love a homebrew formula since I keep my brew packages up to date regularly. I don't update global npm packages usually (one fewer places to worry about). Another reason is that I often switch between node versions and it would be nice to have an independent installation of npm-check-updates so I don't have to reinstall it in every node version.

**Comment by raineorshine** [comment]
Thanks for the explanation. I think for simplicity's sake I'm just going to host it on npm. npm-check-updates is an npm package, so global npm install seems like the right place for it.

> Another reason is that I often switch between node versions and it would be nice to have an independent installation of npm-check-updates so I don't have to reinstall it in every node version.

If you use nvm, `nvm reinstall-packages` is super helpful for this, although I do recognize that it must be run manually for each node version.

**Comment by domoritz** [comment]
Thanks for considering my request and keep up the good work with the package. I've used it for a long time and it makes my workflow much more pleasant.

**Comment by NickLiffen** [comment]
I would also like a +1 for this :) @raineorshine the main reason for me would be updating and keeping tab of versions. I find homebrew mades it really easy to keep updated. Instead of updating all homebrew and node global packages, homebrew just makes things easier. 

I know this has been closed :) Just wanted to chime in 💯 I would also be happy to create the formula :) but wouldn't want to do it without your thoughts :) just thought I would add the above :)
