### ISSUE TITLE
New strategy `eager`: update to the closest higher version accross all tags

### ISSUE THREAD

**Issue by brillout** [raineorshine/npm-check-updates#890]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

I believe `--target latest` should check what tag the current version is on, and then upgrade to the latest version of that tag.

Currently it checks the tag `latest`, even if the current version lives only in another tag such as `next`.

- If the current version lives in tag `latest` => upgrade to the latest version of tag `latest`.
- Otherwise check in what tag the version lives => upgrade to the latest version of that tag.

**Comment by raineorshine** [comment]
Could you provide an example including the dependency as written in the package.json, the version of the `latest` tag, and the version of the `next` tag? That would help me be more specific in my response.

**Comment by brillout** [comment]
```shell
$ npm info vue
dist-tags:
csp: 1.0.28-csp  latest: 2.6.12   next: 3.0.11 
```

My depedency is stuck at `vue@3.0.6` and ncu won't update it.

Btw thanks for your wonderful work, one of my fav pkg.

**Comment by brillout** [comment]
I don't know if npm provides tag history? Would be required to implement what I described in the OP.

**Comment by brillout** [comment]
>  I don't know if npm provides tag history

If it doesn't: searching the closest higher version across all tags would do the trick for most cases though (maybe even all cases).

**Comment by raineorshine** [comment]
Okay, I see. I don't think tags are "smart" enough for this, but I give an alternative suggestion at the end (after I ramble about use cases and design principles 😊)

Similar to a git tag, an npm tag just points to a single version number. If a different version is published to an existing tag, it overwrites the previous version that was at that tag. There is no way to retrieve a history of versions that were published to a given tag. Also, tags are not exclusive, so the same version may be published to more than one tag, such as a version that was on `next` getting published to `latest` after being tested for some time. Thus there is no real way to know which tag a version "lives" on unless the tag is pointing to exactly that version.

Since your dependency declaration is higher than what is published to `latest`, npm-check-updates could infer your intention to check beyond `latest` (at least it doesn't upgrade you *down* to `latest`... that bug was fixed). However there is no way to know that you are specifically wanting to stay up-to-date with `next`. There could be higher versions than `next` that are published to a different tag.

Even if we could come up with a reasonably sane default that covers the major use cases, arguably it is still too complex for npm-check-updates's basic design principle of having predictable, uniform defaults. The fact that npm-check-updates *always* upgrades to the `latest` tag (except a little bit of logic that excludes versions clearly marked as `-beta` or `-pre`) is beneficial to new users and makes reasoning about ncu's behavior easier for everyone.

I recommend running `ncu` twice: once for regular `latest` upgrades and once for specific packages that you want to be at the bleeding edge.

```sh
ncu -x vue                     # upgrade everything except vue
ncu -f vue --target greatest   # upgrade vue to the highest version number available
```

Some day I hope to add per-dependency options that would allow this to be configured in your `.ncurc` and run it as a single command.

Additionally, it would be nice to be able to specify the tag to upgrade to:

```sh
ncu -f vue --target tag:next   # not yet supported
```

**Comment by brillout** [comment]
👍 :-)

> I recommend running ncu twice: once for regular latest upgrades and once for specific packages that you want to be at the bleeding edge.

Yep, that's what I'm currently doing.

IMO a new strategy `eager` would be neat.

Would also play nice with per-pkg strategy config.

**Comment by raineorshine** [comment]
> eager: update to the closest higher version accross all tags

Upgrading to the closest (next) higher version would fall behind if they published multiple versions in between you running `ncu`. I think it would have to be `greatest` or specifying the tag explicitly.

**Comment by brillout** [comment]
I mean: for all dist-tags pick the lowest version that is higher than the current version.

**Comment by raineorshine** [comment]
> I mean: for all dist-tags pick the lowest version that is higher than the current version.

I see. I still think explicitly specifying the tag is better. It's going to be opt-in, you probably know the tag you want, and you probably don't want it to switch around from different tags if a next highest version somehow gets published somewhere else.

**Comment by brillout** [comment]
Makes sense; I guess it should do it only if the current version is > than latest. I'd argue that having a dependency that is not matching any dist-tag is the worst outcome.

**Comment by shadow-light** [comment]
Would warning be an option if not guessing what the user wants? Also just came across this issue with vue not updating and it took me a while to discover I wasn't using the latest version of it as I thought I was.

Perhaps ncu could say `Package "vue" has a version higher than "latest". Running "ncu -f vue --target greatest" may discover an update` or something like that?

**Comment by raineorshine** [comment]
I can see how the behavior would be a bit confusing if you're using higher versions than `latest` and expecting an upgrade. That said, the default behavior of `npm-check-updates` is dead simple: upgrade to the *latest* tag. People sometimes project their own expectations on ncu's behavior. I'm not saying it's unimportant or shouldn't be addressed, just that it should be considered differently than a behavior that is complex or confusing in itself.

If this were widespread I would consider a warning, but only as a last resort. The minimal output of `ncu` is one of its core design principles. I'm not seeing a high number of +1's here so I assume it is only affecting a small handful of people.

You can consider the troubleshooting issue to be part of a broader issue where it is difficult to know *why* a dependency is being upgraded or not. If/when the internal upgrade pipeline is changed to support per-dependency options, I can propagate the *why* information back up for a nice explanatory output that should easily clear up such confusions.
