### ISSUE TITLE
The library is old so I want you to update it.

### ISSUE THREAD

**Issue by famibee** [raineorshine/npm-check-updates#921]
Due to security issues, the library is out of date and I would like you to update it.
セキュリティの問題から、ライブラリが古いので更新して欲しいです。

| Lib | Now | Latest |
|---|---|---|
| cint | ^8.2.1 | 9.1.0 |
| commander | ^6.2.1 | 8.0.0 |
| get-stdin | ^8.0.0 | 9.0.0 |
| p-map | ^4.0.0 | 5.0.0 |

https://david-dm.org/raineorshine/npm-check-updates

**Comment by raineorshine** [comment]
Each of the dependencies listed are breaking and require some changes to upgrade. All other dependencies are upgraded frequently. 

I maintain npm-check-updates as a side project, so I don't hold myself accountable to keeping every dependency up-to-date unless there is a specific bug or security issue. Since you didn't describe a specific bug or security issue, I'm going to close the issue, but please feel free to submit a PR. Thank you!
