### ISSUE TITLE
[FR] `--target` defaults to `minor`

### ISSUE THREAD

**Issue by wenfangdu** [raineorshine/npm-check-updates#923]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---

The current default for `--target` is `latest`, which compares to `minor` is more destructive, had to add `.ncurc.json` in every project to specify `"target": "minor"`, would be great if it defaults to `minor`.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion. I'm glad that `"target": "minor"` meets your needs. 

Actually, the _raisin d'etre_ of npm-check-updates is to _break_ upgrades by forcing them to `lastest`. It was originally created because npm itself didn't have a good way to break semver when starting a new project or keeping a package file at the latest releases. Since then, npm-check-updates has evolved and added many options while retaining its minimal core. While semver `^` or `~` works great for most users who only want to make minor upgrades, some users prefer the feedback and control of `npm-check-updates`. 

For this reason, npm-check-updates will continue to default to `"target": "latest"`.

**Comment by wenfangdu** [comment]
@raineorshine Thanks for the explanation!
